// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CategorySelectInput: typeof import('./components/hobby/CategorySelectInput.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ErrorMessages: typeof import('./components/form/ErrorMessages.vue')['default']
    HobbyCalendar: typeof import('./components/hobby/HobbyCalendar.vue')['default']
    HobbyCard: typeof import('./components/hobby/HobbyCard.vue')['default']
    HobbyList: typeof import('./components/hobby/HobbyList.vue')['default']
    HobbyTable: typeof import('./components/hobby/HobbyTable.vue')['default']
    NewHobbyForm: typeof import('./components/hobby/NewHobbyForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLogin: typeof import('./components/auth/TheLogin.vue')['default']
    TheNavigation: typeof import('./components/TheNavigation.vue')['default']
    TheRegister: typeof import('./components/auth/TheRegister.vue')['default']
  }
}
